##
##  Pothole Map
##  Copyright (c) 2020 by SilentByte <https://www.silentbyte.com/>
##

service: pothole-map

provider:
  name: aws
  region: us-east-1
  runtime: python3.7

functions:
  query:
    handler: potholemap/lambdas.query_handler
    events:
      - http:
          path: query
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
            allowCredentials: false

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-python-requirements

package:
  exclude:
    - venv/**
    - node_modules/**
    - __pycache__/**
    - "*.py[cod]"
    - "*$py.class"
    - .idea/**
    - .serverless/**
    - htmlcov/**
    - .coverage
    - .env*
    - docs/**

custom:
  pythonRequirements:
    dockerizePip: true
