##
##  Pothole Map
##  Copyright (c) 2020 by SilentByte <https://www.silentbyte.com/>
##

service: pothole-map

provider:
  name: aws
  region: us-east-1
  runtime: python3.7

environment:
  DEBUG: ${env:DEBUG}
  PRODUCTION: ${env:PRODUCTION}

  DB_HOST: ${env:DB_HOST}
  DB_PORT: ${env:DB_PORT}
  DB_NAME: ${env:DB_NAME}
  DB_USER: ${env:DB_USER}
  DB_PASSWORD: ${env:DB_PASSWORD}

  QUERY_MAX_RESULT_COUNT: ${env:QUERY_MAX_RESULT_COUNT}
  QUERY_DEFAULT_RESULT_COUNT: ${env:QUERY_DEFAULT_RESULT_COUNT}

functions:
  query:
    handler: potholemap/lambdas.query_handler
    events:
      - http:
          path: query
          method: post
          cors:
            origin: ${env:ACCESS_CONTROL_ALLOW_ORIGIN}
            headers:
              - Content-Type
            allowCredentials: false

  upload:
      handler: potholemap/lambdas.upload_handler
      events:
        - http:
            path: upload
            method: post
            cors:
              origin: ${env:ACCESS_CONTROL_ALLOW_ORIGIN}
              headers:
                - Content-Type
              allowCredentials: false

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-python-requirements

package:
  exclude:
    - venv/**
    - node_modules/**
    - __pycache__/**
    - "*.py[cod]"
    - "*$py.class"
    - .idea/**
    - .serverless/**
    - htmlcov/**
    - .coverage
    - .env*

custom:
  pythonRequirements:
    dockerizePip: true
